;
; File generated by cc65 v 2.18 - Git bf4b195
;
	.fopt		compiler,"cc65 v 2.18 - Git bf4b195"
	.setcpu		"6502"
	.smart		on
	.autoimport	on
	.case		on
	.debuginfo	off
	.importzp	sp, sreg, regsave, regbank
	.importzp	tmp1, tmp2, tmp3, tmp4, ptr1, ptr2, ptr3, ptr4
	.macpack	longbranch
	.forceimport	__STARTUP__
	.import		_cprintf
	.import		_cgetc
	.export		_main

.segment	"RODATA"

S0002:
	.byte	$D0,$52,$45,$53,$53,$20,$41,$20,$4B,$45,$59,$20,$54,$4F,$20,$45
	.byte	$58,$49,$54,$20,$50,$52,$4F,$47,$52,$41,$4D,$0D,$0A,$00
S0001:
	.byte	$C2,$4F,$4F,$54,$20,$46,$49,$4C,$45,$20,$54,$45,$53,$54,$20,$50
	.byte	$52,$4F,$47,$52,$41,$4D,$0D,$0A,$00
S0003:
	.byte	$54,$4F,$20,$C2,$C1,$D3,$C9,$C3,$0D,$0A,$00

; ---------------------------------------------------------------
; int __near__ main (void)
; ---------------------------------------------------------------

.segment	"CODE"

.proc	_main: near

.segment	"CODE"

;
; cprintf("Boot file test program\n\r");
;
	jsr     decsp1
	lda     #<(S0001)
	ldx     #>(S0001)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
;
; cprintf("Press a key to exit program\n\r");
;
	lda     #<(S0002)
	ldx     #>(S0002)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
;
; cprintf("to BASIC\n\r");
;
	lda     #<(S0003)
	ldx     #>(S0003)
	jsr     pushax
	ldy     #$02
	jsr     _cprintf
;
; inChar = cgetc();
;
	jsr     _cgetc
	ldy     #$00
	sta     (sp),y
;
; POKE(ROMSELREG, 0x80);
;
	ldx     #$00
	lda     #$80
	sta     $DF28
;
; __asm__("jmp ($FFFC)");
;
	jmp     ($FFFC)
;
; return 0;
;
	ldx     #$00
	lda     #$00
	jmp     L0001
;
; }
;
L0001:	jsr     incsp1
	rts

.endproc

